name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          echo "BACK_EXPOSE=8080" >> .env
          echo "NGINX_HOST_PORT=8080" >> .env
          echo "NGINX_CONT_PORT=80" >> .env

      - name: Build and start
        run: docker compose up --build -d

      - name: Check response
        run: |
          sleep 5
          curl -f http://localhost:8080 | grep "Hello from Effective Mobile!"

      - name: Stop containers
        if: always()
        run: docker compose down

